// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: foo.sql

package tutorial

import (
	"context"
)

const get_all_users = `-- name: get_all_users :one
select id, email from "user_"
`

func (q *Queries) get_all_users(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, get_all_users)
	var i User
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}
